/**
 * Canonical facility registry — single source of truth for all Ottawa aquatic facilities.
 * Scraping only enriches existing entries; it never creates or hides facilities.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { facilityUrl } from './facilityUrls.js';
import { upsertScrapeDiagnostic } from './db.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');

export const FacilityType = {
  INDOOR_POOL: 'INDOOR_POOL',
  WAVE_POOL: 'WAVE_POOL',
  OUTDOOR_POOL: 'OUTDOOR_POOL',
  WADING_POOL: 'WADING_POOL',
  SPLASH_PAD: 'SPLASH_PAD',
};

export const DataModel = {
  SWIM_SCHEDULE: 'SWIM_SCHEDULE',
  MIXED_SEASONAL: 'MIXED_SEASONAL',
  /** @deprecated use MIXED_SEASONAL for outdoor pools */
  SEASONAL_HOURS: 'SEASONAL_HOURS',
  HOURS_ONLY: 'HOURS_ONLY',
  STATUS_ONLY: 'STATUS_ONLY',
};

export const DisplayStatus = {
  LIVE_OK: 'LIVE_OK',
  SEASONAL: 'SEASONAL',
  HOURS_ONLY: 'HOURS_ONLY',
  STATUS_ONLY: 'STATUS_ONLY',
  BLOCKED: 'BLOCKED',
  PARSE_ISSUE: 'PARSE_ISSUE',
  STALE: 'STALE',
};

/** All aquatic facility types — map/list visibility uses ONLY this set. */
export const ALL_AQUATIC_TYPES = [
  FacilityType.INDOOR_POOL,
  FacilityType.OUTDOOR_POOL,
  FacilityType.WADING_POOL,
  FacilityType.SPLASH_PAD,
  FacilityType.WAVE_POOL,
];

export const AQUATIC_TYPES = new Set(ALL_AQUATIC_TYPES);

/** Minimum registry counts — build fails if below these. */
export const EXPECTED_MINIMUMS = {
  INDOOR_POOL: 18,
  WAVE_POOL: 3,
  OUTDOOR_POOL: 9,
  WADING_POOL: 18,
  SPLASH_PAD: 9,
  /** Marketing / drop-in indoor aquatic total (INDOOR + WAVE). */
  INDOOR_AQUATIC: 21,
};

const LEGACY_SCHEDULE_MODE_MAP = {
  HAS_SWIM_SCHEDULE: DataModel.SWIM_SCHEDULE,
  SEASONAL_ONLY: DataModel.MIXED_SEASONAL,
  OPEN_HOURS_ONLY: DataModel.HOURS_ONLY,
};

const REGISTRY_PATHS = [
  path.join(__dirname, '../data/facilities_registry.json'),
  path.join(ROOT, 'backend/data/facilities_registry.json'),
  path.join(ROOT, 'app/assets/facilities_registry.json'),
];

let _cachedRegistry = null;

function resolveRegistryPath() {
  for (const p of REGISTRY_PATHS) {
    if (fs.existsSync(p)) return p;
  }
  return path.join(__dirname, '../data/facilities_registry.json');
}

/** Load full facility registry from JSON (generated by build-facility-registry.mjs). */
export function loadFacilityRegistry() {
  if (_cachedRegistry) return _cachedRegistry;

  const registryPath = resolveRegistryPath();
  if (!fs.existsSync(registryPath)) {
    const canonicalPath = path.join(ROOT, 'app/assets/facilities_canonical.json');
    if (fs.existsSync(canonicalPath)) {
      const canonical = JSON.parse(fs.readFileSync(canonicalPath, 'utf8'));
      _cachedRegistry = canonical.facilities.map((row) => resolveFacilityRecord(row));
      return _cachedRegistry;
    }
    throw new Error(
      `Facility registry not found at ${registryPath}. Run: node scripts/build-facility-registry.mjs`,
    );
  }

  const payload = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
  _cachedRegistry = (payload.facilities || []).map((row) => resolveFacilityRecord(row));
  return _cachedRegistry;
}

export function clearRegistryCache() {
  _cachedRegistry = null;
}

export function countFacilitiesByType(registry = loadFacilityRegistry()) {
  const counts = {};
  for (const type of ALL_AQUATIC_TYPES) counts[type] = 0;
  for (const f of registry) {
    if (counts[f.type] != null) counts[f.type]++;
  }
  return counts;
}

/**
 * Fail build/CI when registry coverage is below Ottawa minimums.
 * Indoor "21" = INDOOR_POOL + WAVE_POOL (city marketing / drop-in total).
 */
export function assertFacilityCoverage(registry = loadFacilityRegistry()) {
  const counts = countFacilitiesByType(registry);
  const errors = [];

  for (const [type, min] of Object.entries(EXPECTED_MINIMUMS)) {
    if (type === 'INDOOR_AQUATIC') continue;
    const actual = counts[type] || 0;
    if (actual < min) {
      errors.push(`${type}: ${actual} < ${min}`);
    }
  }

  const indoorAquatic =
    (counts[FacilityType.INDOOR_POOL] || 0) + (counts[FacilityType.WAVE_POOL] || 0);
  if (indoorAquatic < EXPECTED_MINIMUMS.INDOOR_AQUATIC) {
    errors.push(
      `indoor pools (INDOOR_POOL+WAVE_POOL): ${indoorAquatic} < ${EXPECTED_MINIMUMS.INDOOR_AQUATIC}`,
    );
  }

  const missingCoords = registry.filter(
    (f) => f.latitude == null || f.longitude == null,
  );
  if (missingCoords.length > 0) {
    errors.push(
      `facilities missing coordinates: ${missingCoords.map((f) => f.id).join(', ')}`,
    );
  }

  if (errors.length > 0) {
    throw new Error(`Facility coverage assertion failed:\n${errors.map((e) => `  - ${e}`).join('\n')}`);
  }

  return { counts, indoorAquatic, total: registry.length };
}

export function isAquaticType(type) {
  return AQUATIC_TYPES.has((type || '').toUpperCase());
}

export function defaultDataModelForType(facilityType) {
  switch (facilityType) {
    case FacilityType.INDOOR_POOL:
    case FacilityType.WAVE_POOL:
      return DataModel.SWIM_SCHEDULE;
    case FacilityType.OUTDOOR_POOL:
      return DataModel.MIXED_SEASONAL;
    case FacilityType.WADING_POOL:
      return DataModel.HOURS_ONLY;
    case FacilityType.SPLASH_PAD:
      return DataModel.HOURS_ONLY;
    default:
      return DataModel.STATUS_ONLY;
  }
}

export function normalizeFacilityType(raw, id = '', name = '') {
  const t = (raw || '').toUpperCase();
  if (AQUATIC_TYPES.has(t)) return t;
  const lower = `${id} ${name}`.toLowerCase();
  if (lower.includes('splash') && lower.includes('pad')) return FacilityType.SPLASH_PAD;
  if (lower.includes('wading')) return FacilityType.WADING_POOL;
  if (lower.includes('wave')) return FacilityType.WAVE_POOL;
  if (lower.includes('outdoor') || _OUTDOOR_IDS.has(id)) return FacilityType.OUTDOOR_POOL;
  return FacilityType.INDOOR_POOL;
}

const _OUTDOOR_IDS = new Set([
  'bearbrook-pool', 'beaverbrook-pool-kanata', 'corkstown-pool', 'crestview-pool',
  'entrance-pool', 'general-burns-pool', 'genest-pool', 'glen-cairn-pool', 'katimavik-pool',
]);

function normalizeDataModel(raw, type) {
  const model = raw?.data_model ?? raw?.dataModel;
  if (model === DataModel.SEASONAL_HOURS && type === FacilityType.OUTDOOR_POOL) {
    return DataModel.MIXED_SEASONAL;
  }
  if (model && Object.values(DataModel).includes(model)) return model;
  return (
    LEGACY_SCHEDULE_MODE_MAP[raw?.schedule_mode] ?? defaultDataModelForType(type)
  );
}

/**
 * Resolve full facility registry entry from canonical row or DB row.
 * MUST be called before pipeline routing.
 */
export function resolveFacilityRecord(raw) {
  const type = normalizeFacilityType(raw.facility_type ?? raw.type, raw.id, raw.name);
  let dataModel = normalizeDataModel(raw, type);

  if (raw.has_swim_schedule === false && dataModel === DataModel.SWIM_SCHEDULE) {
    if (type === FacilityType.OUTDOOR_POOL) {
      dataModel = DataModel.MIXED_SEASONAL;
    }
  }

  const hasSwimSchedule =
    raw.has_swim_schedule != null
      ? Boolean(raw.has_swim_schedule)
      : dataModel === DataModel.SWIM_SCHEDULE;

  const displayStatusDefault = displayStatusForDataModel(dataModel);

  return {
    id: raw.id,
    name: raw.name,
    type,
    dataModel,
    hasSwimSchedule,
    displayStatusDefault,
    scheduleMode: legacyScheduleMode(dataModel),
    region: raw.region ?? null,
    address: raw.address ?? null,
    latitude: raw.latitude ?? raw.lat ?? null,
    longitude: raw.longitude ?? raw.lng ?? null,
    notes: raw.notes ?? null,
    season: raw.season ?? null,
  };
}

export function legacyScheduleMode(dataModel) {
  switch (dataModel) {
    case DataModel.SWIM_SCHEDULE:
      return 'HAS_SWIM_SCHEDULE';
    case DataModel.MIXED_SEASONAL:
    case DataModel.SEASONAL_HOURS:
      return 'SEASONAL_ONLY';
    case DataModel.HOURS_ONLY:
      return 'OPEN_HOURS_ONLY';
    default:
      return 'OPEN_HOURS_ONLY';
  }
}

export function displayStatusForDataModel(dataModel) {
  switch (dataModel) {
    case DataModel.MIXED_SEASONAL:
    case DataModel.SEASONAL_HOURS:
      return DisplayStatus.SEASONAL;
    case DataModel.HOURS_ONLY:
      return DisplayStatus.HOURS_ONLY;
    case DataModel.STATUS_ONLY:
      return DisplayStatus.STATUS_ONLY;
    default:
      return DisplayStatus.LIVE_OK;
  }
}

/** UI label for non-schedule facilities — never show "No schedules". */
export function labelForFacilityType(type) {
  switch (type) {
    case FacilityType.WADING_POOL:
      return 'Open Hours Only';
    case FacilityType.SPLASH_PAD:
      return 'Seasonal Activity Area';
    case FacilityType.OUTDOOR_POOL:
      return 'Seasonal Schedule';
    default:
      return null;
  }
}

export function usesSwimSchedulePipeline(registry) {
  return registry.dataModel === DataModel.SWIM_SCHEDULE && registry.hasSwimSchedule;
}

export function usesSeasonalPipeline(registry) {
  return (
    registry.dataModel === DataModel.MIXED_SEASONAL ||
    registry.dataModel === DataModel.SEASONAL_HOURS ||
    registry.dataModel === DataModel.HOURS_ONLY ||
    registry.dataModel === DataModel.STATUS_ONLY
  );
}

export function labelForDisplayStatus(status) {
  return {
    LIVE_OK: 'Live schedules',
    SEASONAL: 'Seasonal Schedule',
    HOURS_ONLY: 'Open Hours Only',
    STATUS_ONLY: 'Seasonal Activity Area',
    BLOCKED: 'Blocked',
    PARSE_ISSUE: 'Schedule parse issue',
    STALE: 'Stale — last good data preserved',
  }[status] ?? status;
}

export function confidenceScoreForDisplayStatus(status, sessionCount = 0) {
  switch (status) {
    case DisplayStatus.LIVE_OK:
      return sessionCount > 0 ? 0.95 : 0.5;
    case DisplayStatus.SEASONAL:
    case DisplayStatus.HOURS_ONLY:
    case DisplayStatus.STATUS_ONLY:
      return 0.85;
    case DisplayStatus.STALE:
      return 0.9;
    case DisplayStatus.BLOCKED:
    case DisplayStatus.PARSE_ISSUE:
      return 0.1;
    default:
      return 0;
  }
}

/**
 * Insert missing registry facilities on startup — never overwrite scraped schedule data.
 */
export function syncRegistryToDatabase(database) {
  const registry = loadFacilityRegistry();
  assertFacilityCoverage(registry);

  const insertOnly = database.prepare(`
    INSERT INTO facilities (
      id, name, address, lat, lng, type, schedule_mode, data_model,
      has_swim_schedule, display_status, region, url, last_verified, last_updated
    ) VALUES (
      @id, @name, @address, @lat, @lng, @type, @schedule_mode, @data_model,
      @has_swim_schedule, @display_status, @region, @url, @last_verified, @last_updated
    )
    ON CONFLICT(id) DO UPDATE SET
      name = excluded.name,
      address = COALESCE(facilities.address, excluded.address),
      lat = COALESCE(facilities.lat, excluded.lat),
      lng = COALESCE(facilities.lng, excluded.lng),
      type = excluded.type,
      schedule_mode = excluded.schedule_mode,
      data_model = excluded.data_model,
      has_swim_schedule = excluded.has_swim_schedule,
      display_status = COALESCE(facilities.display_status, excluded.display_status),
      region = COALESCE(facilities.region, excluded.region),
      url = COALESCE(facilities.url, excluded.url),
      last_updated = excluded.last_updated
  `);

  const now = Date.now();
  let inserted = 0;
  let updated = 0;

  for (const reg of registry) {
    const existing = database.prepare('SELECT id FROM facilities WHERE id = ?').get(reg.id);
    insertOnly.run({
      id: reg.id,
      name: reg.name,
      address: reg.address,
      lat: reg.latitude,
      lng: reg.longitude,
      type: reg.type,
      schedule_mode: reg.scheduleMode,
      data_model: reg.dataModel,
      has_swim_schedule: reg.hasSwimSchedule ? 1 : 0,
      display_status: reg.displayStatusDefault,
      region: reg.region,
      url: facilityUrl(reg.id),
      last_verified: null,
      last_updated: now,
    });

    if (!existing) {
      inserted++;
      if (!reg.hasSwimSchedule) {
        upsertScrapeDiagnostic(database, reg.id, {
          classification: reg.displayStatusDefault,
          display_status: reg.displayStatusDefault,
          data_source: 'registry',
          quality_score: 2,
          confidence_score: 0.85,
          render_status: 'N/A',
        });
      }
    } else {
      updated++;
    }
  }

  console.log(
    `[registry] syncRegistryToDatabase: ${registry.length} registry entries (${inserted} new, ${updated} merged)`,
  );
  return { total: registry.length, inserted, updated, counts: countFacilitiesByType(registry) };
}

/** @deprecated Use syncRegistryToDatabase */
export async function seedFromAssets(database) {
  return syncRegistryToDatabase(database);
}
